### ISSUE TITLE
access denied?

### ISSUE THREAD

**Issue by CesMak** [CogRob/omnimapper#19]
Just following your youtube video

gives me:
```

omnimapper/docker$ sudo make pull
Using default tag: latest
Error response from daemon: pull access denied for cogrob/omnimapper-dep, repository does not exist or may require 'docker login'
Makefile:24: recipe for target 'pull' failed
make: *** [pull] Error 1

```

**Comment by ruffsl** [comment]
Instead of multiple separate images, I moved them to shared tags some time ago:  
https://hub.docker.com/r/cogrob/omnimapper/tags/

 Note however that Omnimapper is not currently being actively developed, and these images are rather old.

**Comment by BillWSY** [comment]
Obsolete
